services:
  redis:
    container_name: rse_redis
    image: redis:latest
    command: redis-server /usr/local/etc/redis/redis.conf
    volumes:
      - ./settings/redis/redis.conf:/usr/local/etc/redis/redis.conf
    ports:
      - ${REDIS_HOST_PORT}:${REDIS_CONTAINER_PORT}
    networks:
      - rse_redis_net
    restart: unless-stopped
    

networks:
  rse_redis_net:
    driver: bridge
    